### ISSUE TITLE
Can't use mixbox within Unity. 

### ISSUE THREAD

**Issue by pajama** [patriciogonzalezvivo/lygia#103]
I'm getting this error
`undeclared identifier 'rgb2srgb' at Assets/Shaders/lygia/color/mixBox.hlsl(76) (on d3d11)`

Not really sure what's going on.  The issue goes away if I create a new file that is a copy of rgb2srgb with renamed defines and methods, but that's not a good solution to whatever the underlying issue is.

**Comment by patriciogonzalezvivo** [comment]
wow, that's really weird. Have you tried temporally renaming the file? just wondering if it's related to FS or name collisions. maybe somewhere is adding the `.glsl` version of it?
