### ISSUE TITLE
typo in greaterThan.hlsl wont compile

### ISSUE THREAD

**Issue by bmFicg** [patriciogonzalezvivo/lygia#118]
https://github.com/patriciogonzalezvivo/lygia/blob/ebb26d74faf8f6b8aaae04d2b7b89a0e49e207b5/math/greaterThan.hlsl#L7

**Comment by patriciogonzalezvivo** [comment]
https://github.com/patriciogonzalezvivo/lygia/commit/adf1714660e0133dba53cb6e20b37c6d745927b9

thank you!
