### ISSUE TITLE
[Unity] - Delete Lygia.asmdef

### ISSUE THREAD

**Issue by tomorrowevening** [patriciogonzalezvivo/lygia#119]
Assembly Definitions are for C# code, not Graphics, so we can delete this file 👍

```
Assembly for Assembly Definition File 'Assets/Shaders/lygia/Lygia.asmdef' will not be compiled, because it has no scripts associated with it.
```

**Comment by patriciogonzalezvivo** [comment]
https://github.com/patriciogonzalezvivo/lygia/commit/edfccc84808c2c83b8e8ac6ba88efbafbe4b227d

thank you!
