### ISSUE TITLE
discord server link expirred

### ISSUE THREAD

**Issue by waynr** [patriciogonzalezvivo/lygia#120]
At the bottom of the README.md there is a link to `https://shader.zone/` but when I try to join this server discord tells me that the invite has expired.

**Comment by waynr** [comment]
I mostly wanted to join the server to let you know that `lygia.xyz` doesn't seem to be loading for me - neither when I hit it directly in my browser nor when another site attempts to load javascript from the same host (like https://editor.p5js.org/patriciogonzalezvivo/sketches).

**Comment by patriciogonzalezvivo** [comment]
Hi @waynr, thanks for the heads up about the server being down. lygia.xyz and the P5js should work now.
