### ISSUE TITLE
OKLAB conversions to/from RGB are actually linear sRGB

### ISSUE THREAD

**Issue by johnbchron** [patriciogonzalezvivo/lygia#122]
I'm having trouble using the OKLAB/RGB conversions, and this is the cause as best I can tell. The matrix values used match [the source implementation](https://bottosson.github.io/posts/oklab/#converting-from-linear-srgb-to-oklab) for linear sRGB to OKLAB.

This is fine, but an incorrect name introduces confusion. I recommend changing the names from `rgb2oklab` and `oklab2rgb` to `srgb2oklab` and `oklab2srgb`, respectively. Granted I am by no means a color expert and my grasp on these subjects is tenuous at best, so please check my work.

**Comment by patriciogonzalezvivo** [comment]
Good catch! You are right! I will make the name conversions and retro feet linear RGB conversions. Unless you want to make a PR for it.
No pressures!
Thank you for surfacing this up

**Comment by patriciogonzalezvivo** [comment]
@johnbchron let me know if this works for you https://github.com/patriciogonzalezvivo/lygia/commit/f2e7a3e2846bb56d07aba9efe8c7d29274da2e5d

**Comment by johnbchron** [comment]
Yep that works! Thanks!
