### ISSUE TITLE
"smooth" reserved keyword

### ISSUE THREAD

**Issue by kylegrover** [patriciogonzalezvivo/lygia#130]
"smooth" is a reserved keyword in GLSL
https://github.com/patriciogonzalezvivo/lygia/blob/b364f4d6481450ce4aab9a0dac86ad8dc8089125/lighting/pbrLittle.glsl#L58
https://github.com/patriciogonzalezvivo/lygia/blob/b364f4d6481450ce4aab9a0dac86ad8dc8089125/lighting/pbrLittle.glsl#L75

**Comment by patriciogonzalezvivo** [comment]
good catch! Do you mind making a PR?

**Comment by UstymUkhman** [comment]
@kylegrover I hope you don't mind I've created a PR for this 'cause I might need that shader soon. :sweat_smile:
