### ISSUE TITLE
float2 random2(float2 p) in random.hlsl I think is not correct.

### ISSUE THREAD

**Issue by Zvmcevap** [patriciogonzalezvivo/lygia#134]
<code>
float2 random2(float2 p)
{
    float3 p3 = frac(float3(p.x, p.x, p.x) * RANDOM_SCALE.xyz);
    p3 += dot(p3, p3.yzx + 19.19);
    return frac((p3.xx + p3.yz) * p3.zy);
}
</code>
I think it should be, judging by the glsl version:
<code>
float2 random2(float2 p)
{
    float3 p3 = frac(float3(p.x, **p.y**, p.x) * RANDOM_SCALE.xyz);
    p3 += dot(p3, p3.yzx + 19.19);
    return frac((p3.xx + p3.yz) * p3.zy);
}
</code>

Been loosing my mind why voronoi and worley have have been repeating in 2D, changing this solved it.

**Comment by patriciogonzalezvivo** [comment]
You are right! Sorry for the typo. 

Do you mind making a PR?

**Comment by Zvmcevap** [comment]
Sure, I will do it tonight (reading up on how to do it now, as I only ever been programming by myself 🙈).
