### ISSUE TITLE
Blending / Alpha assumptions

### ISSUE THREAD

**Issue by vade** [patriciogonzalezvivo/lygia#139]
Quick q

I notice that all blending assumes alpha component is reset to 1. 

Curious - for image processing, this isnt always helpful. Might we add blending variants which support vec4 /float4 ins and outs? 

 Also should we add Porter / Duff composing modes like Over/Under etc?

**Comment by patriciogonzalezvivo** [comment]
@vade !! you are totally right. it's only 100% correct on RGB. I started using fourth components out of convenience (specially helpful for when using MACROS and you don't want to worry if it's 3 or 4 components). 
Also yes, proper alpha support should consider Porter/Duff. Super open to improve and re design.
I'm so glad to see you here : )

Thank you!
