### ISSUE TITLE
Undefined identifier u_LightColor

### ISSUE THREAD

**Issue by chickenSandwich** [patriciogonzalezvivo/lygia#17]
I believe that `u_LightColor` should be replaced with `LIGHT_COLOR`:
https://github.com/patriciogonzalezvivo/lygia/blob/f73d507bec46656997a655ca0bb0460151341903/lighting/pbrLittle.glsl#L96

**Comment by patriciogonzalezvivo** [comment]
Correct! Do you mind pushing a PR to fix it?

**Comment by chickenSandwich** [comment]
Ok!

**Comment by chickenSandwich** [comment]
#18 Fixed
