### ISSUE TITLE
License for color/blend/* 

### ISSUE THREAD

**Issue by soundasleep** [patriciogonzalezvivo/lygia#19]
Could all of the shaders in /color/blend/* be under a MIT license (they're currently "TODO")? Looks to be a copy of https://github.com/jamieowen/glsl-blend which is under MIT.

**Comment by patriciogonzalezvivo** [comment]
Awesome! Thanks for tracking it down, do you mind adding the license?

**Comment by patriciogonzalezvivo** [comment]
https://github.com/patriciogonzalezvivo/lygia/commit/620477339e3106173e9895c346f2455de921c340

**Comment by soundasleep** [comment]
You beat me to it! 😅 Thanks for an incredible library.
