### ISSUE TITLE
Lang specific documentation and compatibility notes

### ISSUE THREAD

**Issue by vade** [patriciogonzalezvivo/lygia#201]
Might be good to have an official space in the repo that clarifies ongoing language compatibility and porting status.

this would be pretty easy with the top level language folders, just throw readme's underneath each language.

**Comment by patriciogonzalezvivo** [comment]
Ideas:
* creating `/README_METAL.md`, `/README_WGSL.md`, `/README_CUDA.md`, `/README_GLSL.md`, `/README_HLSL.md`, etc for specific documentations on the port and design changes. @sdedovic added some WGSL specific to the `DESIGN.md` but thouse could live on `README_WGSL.md`

* For porting status I could automate something on the server that construct a page feeding and comparing the present files between:
  * https://lygia.xyz/glsl.json
  * https://lygia.xyz/glsl.json
  * https://lygia.xyz/msl.json
  * https://lygia.xyz/wgsl.json
  * ...

**Comment by vade** [comment]
I'll add a README_METAL.md in my repo and in my next PR put the running notes on the porting status and any 'gotchas'

**Comment by patriciogonzalezvivo** [comment]
love it

**Comment by vade** [comment]
Added `README_METAL.md` to the latest metal PR, which now keeps track of progress.
