### ISSUE TITLE
Raymarching Pipeline

### ISSUE THREAD

**Issue by shadielhajj** [patriciogonzalezvivo/lygia#205]
Starting this convo to coordinate work on the Raymarching pipeline.

Next steps for me are completely overhauling the volume rendering sub-system and allowing it to co-exist with PBR in the same scene.

I will also so refactor `RAYMARCH_RETURN` to make it more readable and less intrusive, while maintaining performance.

I will be working mainly on `raymarch.glsl`, `render.glsl` and `volume.glsl`.
@patriciogonzalezvivo please let me know if you need to make major modifications to these files, so we can coordinate and avoid conflicts.

**Comment by patriciogonzalezvivo** [comment]
Beautiful, I will not touch them then. Thank you for the heads up!

ps: I'm slowly fixing raymarching examples to catch up with the new specs 
https://editor.p5js.org/patriciogonzalezvivo/sketches/ZKhZI15qP

**Comment by shadielhajj** [comment]
Implemented in #206!
