### ISSUE TITLE
Blending + Compositing for Float 4 colors

### ISSUE THREAD

**Issue by vade** [patriciogonzalezvivo/lygia#208]
Hey I wanted to more formally discuss compositing / blending this now that I've got some handles on Lygia.

- Ive got a branch that introduces Porter Duff compositing operators (Metal only for now). Basically Ive added a `compositing` folder with a top level `compositing` include, which implements (without any blending)

   - compositeXor.msl
   - destinationAtop.msl
   - destinationIn.msl
   - destinationOut.msl
   - destinationOver.msl
   - sourceAtop.msl
   - sourceIn.msl
   - sourceOut.msl
   - sourceOver.msl

- The current blending operations only work for float3's, and I'd love to extend them to for float 4's which sort of gets into some gnarly assumptions about alpha multiplication etc. I'll be honest, ive forgotten the best practices here and would rather open a discussion about it. 

- In theory, the Porter Duff and Blending math can be combined to allow for more blending options, such as Hard Light  + Destination Over blending which can match more closely the "Layer" processing in tools like Photoshop (think a blend mode with alpha channel content with opacity + some arbitrary alpha fill setting)

- See https://ssp.impulsetrain.com/porterduff.html

<img width="506" alt="image" src="https://github.com/user-attachments/assets/f419502a-3673-4e35-a898-8f91a55079b0">

**Comment by patriciogonzalezvivo** [comment]
Love it! This is the right time to make this kind of change. We are building v1.3 which will have other breaking changes so let's pull the plug and make things have more sense : )

**Comment by vade** [comment]
This is addressed in #222

**Comment by vade** [comment]
Closed (at least WRT to metal) :)
