### ISSUE TITLE
f0 parameter of a PBR material

### ISSUE THREAD

**Issue by gzozulin** [patriciogonzalezvivo/lygia#40]
Hi @patriciogonzalezvivo, quick question on Lygia, if you do not mind:
How to use the f0 parameter of a PBR material? Is it a library value, or do I need to calculate it myself?

Here is a sample of usage in my rendering pipeline:
```glsl
vec4 materialPbr(
    const Hit hit,
    float ior, float f0, float density, float blendCoeff,
    sampler2D samplerAlbedo, sampler2D samplerMetallic,
    sampler2D samplerRoughness, sampler2D samplerNormal,
    sampler2D samplerAO, sampler2D samplerEmission)
{
    vec3 blend = triPlanarBlend(hit.normal, blendCoeff);

    surfacePosition         = hit.point;

    Material pbrMaterial    = materialNew();
    pbrMaterial.position    = hit.point;

    pbrMaterial.normal      = whiteoutBlend(hit.point, hit.normal, blend, density, samplerNormal);

    pbrMaterial.albedo      = triPlanarMapping(samplerAlbedo, hit.point, blend, density);
    pbrMaterial.roughness   = triPlanarMapping(samplerRoughness, hit.point, blend, density).r;
    pbrMaterial.metallic    = triPlanarMapping(samplerMetallic, hit.point, blend, density).r;
    pbrMaterial.ambientOcclusion = triPlanarMapping(samplerAO, hit.point, blend, density).r;
    pbrMaterial.emissive    = triPlanarMapping(samplerEmission, hit.point, blend, density).rgb;

    pbrMaterial.ior         = vec3(ior);         // Index of Refraction (refractive materials only)
    pbrMaterial.f0          = vec3(f0);          // reflectance at 0 degree

    //pbrMaterial.shadow      = 1.0;             // default 1.0
    //pbrMaterial.clearCoat   = 0.9;
    //pbrMaterial.clearCoatRoughness = 0.9;

    return pbr(pbrMaterial);
}
```

**Comment by patriciogonzalezvivo** [comment]
Hi @gzozulin! Good question, as until recently was a parameter that was needed to be precalculated for performance reasons (to save arithmetic instructions),  that's how how `pbr.glsl` uses it https://github.com/patriciogonzalezvivo/lygia/blob/main/lighting/pbr.glsl#L45

But on the addition of `pbrGlass.glsl` I added an IOR parameter to the material https://github.com/patriciogonzalezvivo/lygia/blob/main/lighting/pbrGlass.glsl#L49 from which f0 is calculated. 

So at the time you could take any other path. I'm curious for what you think about it, and if it's worth calculating the value on real-time.

**Comment by gzozulin** [comment]
Hello @patriciogonzalezvivo, sorry for the late response - I was away on vacation,
IMHO, the relaxed approach would be to use a recalculated value and provide a table for the most used ones.

For clear coat and glass, it will be beneficial to just override the value with the one calculated in real time

**Comment by patriciogonzalezvivo** [comment]
That sound great. Do you want to give it a try? If not, I can circle back to it in some weeks.
Thank you

**Comment by patriciogonzalezvivo** [comment]
@gzozulin Thank you for the feedback. Did you had the chance to try the new approach?

**Comment by patriciogonzalezvivo** [comment]
@gzozulin I will close this for the moment. Feel free to open it back again if you think it havent been addressed
