### ISSUE TITLE
Triangular tiles - triTile

### ISSUE THREAD

**Issue by mathiasbredholt** [patriciogonzalezvivo/lygia#45]
Just a quick suggestion here, I made a function for creating triangular tiles as I thought it could be a nice addition to the existing hex and square tiles. The code is based on FabriceNeyret2's [hexagonal tiling tuto](https://www.shadertoy.com/view/4dKXR3).

As the code probably can be improved I just included it here instead of filing a PR. If you prefer a PR @patriciogonzalezvivo, I can definitely do that as well. 

I'm not sure whether the barycentric coords should be optional as an bool argument or that we should just prefer one over the other. Alternatively, we could have `triTile()` and `triTileBaryCentric()`?

```
vec4 triTile(vec2 st) {
  // based on 
  // FabriceNeyret2 hexagonal tiling tuto
  // https://www.shadertoy.com/view/4dKXR3
  st *= mat2(1,-1./1.73, 0,2./1.73);         // conversion to hexagonal coordinates 
  vec3 g = vec3(st,1.-st.x-st.y);
  vec3 id = floor(g);                        // cell id
  g = fract(g);                              // diamond coords
  return length(g) > 1. ? vec4(g.xy, id.xy) : vec4(g.xy, id.yz);
  // barycentric coords, should this be optional?
  // return length(g) > 1. ? vec4(g.xy, id.xy) : vec4(1. - g.xy, id.yz);
}
```
Here's an example:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/8356424/221436098-a57c4865-beb0-40e0-8dd9-0fd5e5c0f7f2.png">

**Comment by patriciogonzalezvivo** [comment]
Hi @mathiasbredholt this is a great contribution! Do you mind making it into a PR?

**Comment by mathiasbredholt** [comment]
I will!
