### ISSUE TITLE
psrdnoise

### ISSUE THREAD

**Issue by stegu** [patriciogonzalezvivo/lygia#56]
Sorry to make a fuss, but your license information for "psrdnoise" is wrong in several ways. The MIT license is not "non-commercial", it's free for any use as long as you include the license information (which you do not, hence you are actually in violation of the license). Furthermore, whereas the code was written by me and Ian, the company Ashima Arts has not existed for a decade, and I never worked there, so please include the proper license header, as found in our original code: https://github.com/stegu/psrdnoise/tree/main/src

Also, consider providing a link back to the original repo, as we will (hopefully) keep maintaining that code for quite some time.

Our livelihoods as researchers depend entirely on citation and reputation. This is why I am being so picky about the terms of the MIT license. It's the most permissive license we could find while still making sure we get credit for the code.

**Comment by stegu** [comment]
Thank you!

You can play a bit fast and loose with the lengthy license text if you
want. We are happy with just a link to it, such as:

"Copyright 2021-2023 by Stefan Gustavson and Ian McEwan.
Published under the terms of the MIT license:
https://opensource.org/license/mit/"

I usually attach this summary as well:

"In short, you may do whatever you like with this code, provided that our
names remain attached for credit, and that you include a mention of the MIT
license. You can do that by simply keeping these lines of comments."

**Comment by patriciogonzalezvivo** [comment]
That's a nice idea. I will take you on it. https://github.com/patriciogonzalezvivo/lygia/commit/ea392510d1ca41dbfb9300a18e7ba572cbd4fd20

BTW, big thank you for all your work. `snoise` is such a helpful and omnipresent algorithm. Big fan of your work.
And sorry again for the missing license on Psdrnoise. Also please feel free to make changes on the description or code. 
I would love to add also a reference to the paper or articles about it.

**Comment by stegu** [comment]
Thanks for your kind words! I have been pointing my students to
thebookofshaders.com for years, so your work is appreciated as well!

A couple of years ago I had plans for teaming up with a local colleague and
writing a book on procedural textures, and asking for your permission to
use some great descriptions and examples from that site, but then I got hit
with Covid, and I'm still struggling with the after effects, so those plans
have been put on ice for the time being. It's still on my bucket list,
though. :)

**Comment by patriciogonzalezvivo** [comment]
Oh, I'm very sorry to hear that. Some members of my family are also struggling with the effects of long COVID.
Let me know how can I help. I would love to collaborate on any form you can think would be suitable.
I started an extension deck of cards for http://pixelspiritdeck.com/ about patterns with shaders... but then we had our second kid and life's complexity went wild

**Comment by stegu** [comment]
Enjoy that "complication", i.e. live and have fun doing it, and let me get
back to you about the book project when I get more up to speed!
