### ISSUE TITLE
compatibility with ogl

### ISSUE THREAD

**Issue by kujohn** [patriciogonzalezvivo/lygia#69]
Is there a way to get lygia to be compatible with https://github.com/oframe/ogl ?

**Comment by kujohn** [comment]
never mind, it works fine using the cloud resolver

**Comment by patriciogonzalezvivo** [comment]
If you have something to share using ogl, I would love to feature it as an integration example

**Comment by kujohn** [comment]
https://github.com/kujohn/lygia_ogl_examples

Nothing fancy. It's also just using vite, so possibly could just have another js file in https://github.com/patriciogonzalezvivo/lygia_threejs_examples

**Comment by patriciogonzalezvivo** [comment]
Perfect! Added to the list! thank you!
