### ISSUE TITLE
A new integration example

### ISSUE THREAD

**Issue by cdaein** [patriciogonzalezvivo/lygia#72]
Hi,
I have a creative coding helper package [`create-ssam`](https://github.com/cdaein/create-ssam) that comes with LYGIA + OGL or Three.js templates for a fullscreen shader. Will it be helpful to add the link to the examples in README?

It comes with a few extra helpful features such as video(gif, webm, mp4) exports, git image snapshot for archival, etc. which might be useful for some people.

**Comment by patriciogonzalezvivo** [comment]
That would be great! Thank you!
